---
title: "R Notebook"
# output: html_notebook
editor_options: 
  chunk_output_type: console
output: 
  html_notebook: 
    fig_caption: yes
fig_width: 6 
fig_height: 4 
---



```{r}
library(FIELDimageR)
library(FIELDimageR.Extra)
library(raster)
library(terra)
library(mapview)
library(sf)
library(stars)
```

```{r}
# Open the orthomosaic
EX1 <- rast("/phenotype_extraction-main/downsampled_orthos/6_16_2023_F120_Beans_P4_15m_RGB_transparent_mosaic_group1_downsample.tif")

# Reduce resolution
EX1<-aggregate(EX1, fact=4)

# Plot the image
plotRGB(EX1, r = 1, g = 2, b =3)
```

```{r, fig.align = "left"}
# Crop the image - interactive
EX1.Crop <- rast(fieldCrop(mosaic = EX1)) #, fast.plot=T)
```

```{r}
# Remove the soil pixels, keep plant pixels
EX1.RemSoil <- rast(fieldMask(mosaic = EX1.Crop, Red = 1, Green = 2, Blue = 3, index = "HUE"))
```

```{r}
### Field map identification 
# Must add rows to fieldmap for split rows
DataTable<-read.csv("/phenotype_extraction-main/fieldmaps/F120_beans_2023_fieldmap.csv",header = T)  
fieldMap<-fieldMap(fieldPlot=DataTable$plot, fieldRow=DataTable$column, fieldColumn=DataTable$range, decreasing=T)

# Create a shapefile - interactive
# It is very important to highlight that four points need to be set at the corners of the trial according to the
# following sequence (1st point) top left corner, (2nd point) top right corner, (3rd point) bottom right
# corner, and (4th point) bottom left corner.(i.e. clockwise from the top left)
EX1.Shape<-fieldShape_render(mosaic = EX1.RemSoil, ncols = 19, nrows = 26, fieldMap = fieldMap, fieldData = DataTable, PlotID = "plot")

# View Shapefile
fieldView(mosaic = EX1.RemSoil,
          fieldShape = EX1.Shape,
          type = 2,
          alpha = 0.2)

```

```{r}
# Editing plot grid shapefile: See https://github.com/filipematias23/FIELDimageR.Extra?tab=readme-ov-file#p4 for more info
EX1.Shape<- fieldShape_edit(mosaic=EX1.RemSoil,
                            fieldShape=EX1.Shape)

# Checking the edited plot grid shapefile:
fieldView(mosaic = EX1.RemSoil,
          fieldShape = EX1.Shape,
          type = 2,
          alpha = 0.2)
```


```{r}
# Set the output file name
output_file <- "shapefile/F120_beans_2023.shp"

# Save the shapefile to a file
st_write(EX1.Shape, dsn = output_file, driver = "ESRI Shapefile")
```