---
title: "R Notebook"
# output: html_notebook
editor_options: 
  chunk_output_type: console
output: 
  html_notebook: 
    fig_caption: yes
fig_width: 6 
fig_height: 4 
---

# Load libraries
```{r}
library(FIELDimageR)
library(FIELDimageR.Extra)
library(raster)
library(terra)
library(mapview)
library(sf)
library(stars)
```

# Process all orthomosaics
```{r}
# Set the path to the "downsampled_orthos" folder
folder_path <- "./downsampled_orthos/"

# Get a list of all files ending in "_downsample.tif"
files <- list.files(path = folder_path, pattern = "_downsample\\.tif$")

# Check using single file
ortho_path <- files[4]

# Iterate through the files
for (ortho_path in files) {
  
  # Remove the ".tif" substring from the ortho_path string
  result <- gsub(".tif", "", ortho_path, fixed = TRUE)
  
  # Print the result
  print(result)
  
  # Open the orthomosaic
  EX1 <- rast(file.path(folder_path, ortho_path))
  # EX1<-aggregate(EX1, fact=4)
  # plotRGB(EX1, r = 1, g = 2, b =3)

  # Remove soil pixels
  EX1.RemSoil <- fieldMask(mosaic = EX1, Red = 1, Green = 2, Blue = 3, index = "HUE")

  # Open shapefile and add to the orthomosaic
  EX1.Shape<- st_read("shapefile/F120_beans_2023.shp") 

  # Calculate canopy cover
  EX1.Canopy<-fieldArea(mosaic = EX1.RemSoil$newMosaic, fieldShape = EX1.Shape)

  # Calculate vegetation indices
  EX1.Indices<- fieldIndex(mosaic = EX1.RemSoil$newMosaic, Red = 1, Green = 2, Blue = 3,
                          index = c("NGRDI","BGI", "GLI", "BI", "SI", "VARI"),
                          plot = FALSE)

  # Visualize the indices
  EX1.Info<- fieldInfo_extra(mosaic = EX1.Indices, fieldShape = EX1.Shape)
  fieldView(mosaic=EX1.RemSoil$newMosaic,
            fieldShape=EX1.Info,
            plotCol = "VARI",
            col_grid = c("red","blue"),
            type = 2,
            alpha = 0.5)

  # Combine inidices and canopy cover
  indices_data <- as.data.frame(EX1.Info)[,-dim(EX1.Info)[2]] %>% dplyr::select(-matches(result))
  canopy_cover_data <- as.data.frame(EX1.Canopy)[,-dim(EX1.Canopy)[2]] %>% dplyr::select(PlotID, AreaPercentage)
  
  # Merge the dataframes using the index column
  merged_data <- merge(indices_data, canopy_cover_data, by = "PlotID")

  # Add ".csv" to the end of the result string
  result <- paste0("./outputs/", result, ".csv")

   # Save output to file
  if(file.exists(result)){
    data <- read.csv(result)
    merged_data <- merge(merged_data, data, by ="PlotID")
    write.csv(merged_data[,-1], file = result, row.names = FALSE)
    } else{
  write.csv(merged_data, file = result, row.names = FALSE)
  }
  
  rm(result, EX1, canopy_cover_data, merged_data)
  
}
```